Frontend:
  impl: SimpleO3
  clock_ratio: 8
  num_expected_insts: 300000
  traces: 
    - ../../ramulator2/example_inst.trace

  Translation:
    impl: RandomTranslation
    max_addr: 2147483648
              

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: GDDR6
    org:
      preset: GDDR6_8Gb_x16
      channel: 2 
      rank: 2
    timing:
      preset: GDDR6_2000_1250mV_quad
    RFM:


  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
        impl: ClosedRowPolicy
        cap: 4
    plugins:

  AddrMapper:
    impl: RoBaRaCoCh
